config/routes.rb
  Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'pages#home'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :decisions
  resources :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :decision
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/decision.rb
class Decision < ApplicationRecord
  enum type: { anonymous_question: 0, public_question: 1 }

  Gutentag::ActiveRecord.call self

  extend FriendlyId
  friendly_id :question_text, use: :slugged

  belongs_to :user, optional: true
  has_many :answers

end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  def self.find_for_oauth(auth)
    create_with(name: auth.extra.raw_info.name).find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ApplicationRecord
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :identities, dependent: :destroy
  has_many :decisions, dependent: :nullify
  has_many :answers, dependent: :nullify

  validates_format_of :email, without: TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource || identity.user || User.where(email: auth.info.email).first || create_from_oauth(auth)

    # for already logged-in users, adding an identity
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def self.create_from_oauth(auth)
    byebug
    user = new(
      email: auth.info.email || "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
      password: Devise.friendly_token[0,20],
      image_url: oauth_image(auth),
      first_name: oauth_first_name(auth),
      last_name: oauth_last_name(auth),
      nick_name: auth.info.name,
    )
    user.skip_confirmation!
    user.save!
    user
  end

  def self.oauth_image(auth)
    case auth.provider
    when 'facebook' then auth.info.image.gsub('http', 'https')
    when 'twitter' then auth.info.profile_image_url_https
    else '/assets/avatar'
    end
  end

  def self.oauth_first_name(auth)
    auth.info.name.split(' ').first
  end

  def self.oauth_last_name(auth)
    auth.info.name.split(' ').drop(1).join(' ')
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    answer = Answer.create user: current_user, decision_id: params[:decision_id], content: params[:content], answer_option: params[:answer_option]
    render json: { answer: answer }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  def show
    @decision = Decision.friendly.find params[:id]
  end

  def new
  end

  def create
    decision = Decision.new user: current_user, question_html: params[:question_html], options: params[:options], question_text: params[:question_text], deadline: params[:deadline]
    decision.tag_names = params[:tags]
    if decision.save
      render json: { decision: decision }
    else
      render json: { resp: 'something happened' }
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(request.env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linked_in, :github].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @decisions = Decision.includes(:user, answers: [:user]).all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, bypass: true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish_signup
    if request.patch? && params[:user]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, bypass: true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ]
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/decisions/new.html.slim
.container.pt-4.pb-5
  .row
    .col-lg-8.offset-lg-2
      #decision-form

= javascript_pack_tag 'decisions'

app/views/decisions/show.html.slim
.container.pt-4.pb-5
  .row
    .col-lg-3
      .card.card-profile.mb-4
        .card-header style=("background-image: url(assets/img/iceland.jpg);")
        .card-body.text-center
          a href="profile/index.html"
            img.card-profile-img src="assets/img/avatar-dhg.png" /
          h6.card-title
            a.text-inherit href="profile/index.html"  Dave Gamache
          p.mb-4 I wish i was a little bit taller, wish i was a baller, wish i had a girl… also.
          ul.card-menu
            li.card-menu-item
              a.text-inherit data-toggle="modal" href="#userModal"
                | Friends
              h6.my-0 12M
            li.card-menu-item
              a.text-inherit data-toggle="modal" href="#userModal"
                | Enemies
              h6.my-0 1
    .col-lg-6
      #decisions data=@decision.to_json(include: [answers: [:user], :user])


    .col-lg-3
      .card.mb-4.d-none.d-lg-block
        .card-body
          h6.mb-3 Sponsored
          div data-grid="images" data-target-height="150"
            img.media-object data-action="zoom" data-height="640" data-width="640" src="assets/img/instagram_2.jpg" /
          p
            strong It might be time to visit Iceland.
            | Iceland is so chill, and everything looks cool here. Also, we heard the people are pretty nice. What are you waiting for?
          button.btn.btn-outline-primary.btn-sm Buy a ticket
      .card.mb-4.d-none.d-lg-block
        .card-body
          h6.mb-3
            | Likes
            small
              | ·
              a href="#"  View All
          ul.media-list.media-list-stream
            li.media.mb-2
              img.media-object.d-flex.align-self-start.mr-3 src="assets/img/avatar-fat.jpg" /
              .media-body
                strong Jacob Thornton
                | @fat
                .media-body-actions
                  button.btn.btn-outline-primary.btn-sm
                    span.icon.icon-add-user
                    | Follow
            li.media
              a.media-left href="#"
                img.media-object.d-flex.align-self-start.mr-3 src="assets/img/avatar-mdo.png" /
              .media-body
                strong Mark Otto
                | @mdo
                .media-body-actions
                  button.btn.btn-outline-primary.btn-sm
                    span.icon.icon-add-user
                    | Follow
        .card-footer
          | Dave really likes these nerds, no one knows why though.
      .card.card-link-list
        .card-body
          | © 2018 Bootstrap
          a href="#"  About
          a href="#"  Help
          a href="#"  Terms
          a href="#"  Privacy
          a href="#"  Cookies
          a href="#"  Ads
          a href="#"  Info
          a href="#"  Brand
          a href="#"  Blog
          a href="#"  Status
          a href="#"  Apps
          a href="#"  Jobs
          a href="#"  Advertise


= javascript_pack_tag 'decisions'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta content='IE=edge' http-equiv='X-UA-Compatible'
    meta content='width=device-width, initial-scale=1' name='viewport'
    meta name='description' content=""
    meta name='keywords'    content=""

    title = content_for?(:title) ? yield(:title) : 'Reezolver'

    = csrf_meta_tags
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:400,300,600', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body.with-top-navbar class="c-#{controller_path.gsub(/\//, '-')} a-#{action_name}" data-env=Rails.env
    header
      = render '/shared/navbar_main'

    main role='main'
      #content
        = yield

    footer
      / = render '/shared/footer'

app/views/pages/home.html.slim
.container.pt-4.pb-5
  .row
    .col-lg-3
      .card.d-none.d-lg-block
        .card-body
          h6.mb-3
            | Trending Searches
          ul.list-unstyled.list-spaced
            li
              a href="#"  #Bootstrap
            li
              a href="#"  Mdo for pres
    .col-lg-6
      #decisions data=@decisions.to_json(include: [:user, answers: { include: :user }])
    .col-lg-3
      .card.mb-4.d-none.d-lg-block
        .card-body
          h6.mb-3 Sponsored
          div data-grid="images" data-target-height="150"
            img.media-object data-action="zoom" data-height="640" data-width="640" src="assets/img/instagram_2.jpg" /
          p
            strong It might be time to visit Iceland.
            | Iceland is so chill, and everything looks cool here. Also, we heard the people are pretty nice. What are you waiting for?
          button.btn.btn-outline-primary.btn-sm Buy a ticket


= javascript_pack_tag 'decisions'

app/views/shared/_navbar_main.html.slim
nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-primary.app-navbar
  .container
    a.navbar-brand href="index.html"
      img alt="brand" src="assets/img/brand-white.png" /
    button.navbar-toggler.navbar-toggler-right.d-md-none aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarResponsive" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      - if current_user
        ul.navbar-nav.mr-auto
          li.nav-item.d-md-none
            a.nav-link href="notifications/index.html"  Notifications
          li.nav-item.d-md-none
            a.nav-link data-action="growl"  Growl
          li.nav-item.d-md-none
            a.nav-link href="login/index.html"  Logout
      - else
        ul.navbar-nav.mr-auto
          li.nav-item.d-md-none
            a.nav-link href="notifications/index.html"  Login
      form.form-inline.float-right.d-none.d-md-flex
        input.form-control data-action="grow" placeholder="Search" type="text" /
      - if current_user
        ul.nav.navbar-nav.float-right.mr-0.d-none.d-md-flex id="#js-popoverContent"
          li.nav-item
            a.app-notifications.nav-link href="notifications/index.html"
              span.icon.icon-bell
          li.nav-item.ml-2
            button.btn.btn-default.navbar-btn.navbar-btn-avatar data-toggle="popover"
              img.rounded-circle src=(current_user.image_url || '/assets/avatar.png')
          li.nav-item.ml-2
            = link_to 'sign out', destroy_user_session_path, method: :delete, class: 'popover-link'
        ul#js-popoverContent.nav.navbar-nav.d-none
          li.nav-item
            a.nav-link data-action="growl" href="#"  Growl
          li.nav-item
            a.nav-link href="login/index.html"  Logout
      - else
        ul.nav.navbar-nav.float-right.mr-0.d-none.d-md-flex id="#js-popoverContent"
          = link_to 'Login', new_user_session_path, class: 'nav-link'

app/views/users/finish_signup.html.slim
.container-fluid.container-fill-height
  .container-content-middle
    = form_for(current_user, as: 'user', url: finish_signup_path(current_user), html: { class: 'mx-auto text-center app-login-form', role: 'form' }) do |f|
      - if @show_errors && current_user.errors.any?
        #error_explanation
          - current_user.errors.full_messages.each do |msg|
            = msg
      .form-group
        = f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control', placeholder: 'email'
        p.help-block Please confirm your email address. No spam.
      = f.submit 'Continue', class: 'btn btn-primary'
/ #add-email.container
/   h1 Add Email
/   = form_for(current_user, as: 'user', url: finish_signup_path(current_user), html: { role: 'form'}) do |f|
/     - if @show_errors && current_user.errors.any?
/       #error_explanation
/         - current_user.errors.full_messages.each do |msg|
/           = msg
/     .form-group
/       = f.label :email
/       .controls
/         = f.text_field :email, autofocus: true, value: '', class: 'form-control input-lg', placeholder: 'Example: email@me.com'
/         p.help-block Please confirm your email address. No spam.
/     .actions
/       = f.submit 'Continue', class: 'btn btn-primary'